### ISSUE TITLE
figma 인터페이스 제작

### ISSUE THREAD

**Issue by soargrape10** [CAP-team05/Mixby#11]
## Issue 세부 내용
Mixby화면 제작

무슨 이슈인가요?

**Comment by soargrape10** [comment]
### Figma로 Mixby 메인화면

![스크린샷 2024-10-11 003253](https://github.com/user-attachments/assets/d05a42c5-b16b-4f8e-813b-f6955be0423f)

Figma로 가장 처음 메인화면 프로토타입 제작

**Comment by handlecusion** [comment]
#15 피드백 반영한 @ahnjh05141 콘티
# 콘티
![KakaoTalk_Photo_2024-10-11-17-39-43](https://github.com/user-attachments/assets/4b4d4270-eae0-4caf-a3c3-4d97a40aaee6)

**Comment by handlecusion** [comment]
새로운 콘티로 작업 진행 중
![image](https://github.com/user-attachments/assets/3ebe8d00-9d90-426b-bb65-b2c0f3cc5763)

**Comment by handlecusion** [comment]
[figma](https://www.figma.com/design/OTa4t2bVuEgZEefDxcnMNy/Mixby?node-id=0-1&node-type=canvas&t=x91cI9QMVlk8Rb08-0)
현재 피그마 링크
