### ISSUE TITLE
1차 progress meeting

### ISSUE THREAD

**Issue by handlecusion** [CAP-team05/Mixby#15]
## Issue 세부 내용

10/11 1차 progress 피드백 진행
208관 503호

피드백 정리 자료 첨부
[1차 progress 피드백.pdf](https://github.com/user-attachments/files/17337850/1.progress.pdf)
wiki 페이지에도 정리되어 있습니다.

**Comment by soargrape10** [comment]
👌

**Comment by handlecusion** [comment]
개인화로 인한 문서 수정 ✅ 
이에 알맞는 인터페이스로 수정 미완
(픽셀 게임 형식으로 만들다가 너무 게임에 가까워져서 다른 감성적인 디자인으로 접근

**Comment by handlecusion** [comment]
수정은 아직 완료하지 않았지만 컨셉은 확정
